# Generated by Django 5.2.16 on 2026-08-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_add_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='contact_person',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='accent_color',
            field=models.CharField(choices=[('indigo', 'Indigo'), ('ocean', 'Ocean Blue'), ('teal', 'Teal'), ('rose', 'Rose'), ('violet', 'Violet'), ('emerald', 'Emerald')], default='indigo', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='animations_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='border_radius',
            field=models.CharField(choices=[('sharp', 'Sharp (0px)'), ('rounded', 'Rounded (8px)'), ('extra-rounded', 'Extra Rounded (16px)')], default='rounded', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='compact_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='font',
            field=models.CharField(choices=[('plus-jakarta', 'Plus Jakarta Sans'), ('inter', 'Inter'), ('poppins', 'Poppins'), ('outfit', 'Outfit')], default='plus-jakarta', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='reduced_motion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('organizer', 'Organizer'), ('volunteer', 'Volunteer'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Light'), ('dark', 'Dark'), ('system', 'System')], default='light', max_length=15),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50),
        ),
        migrations.AddField(
            model_name='venue',
            name='available_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='available_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='venue',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='venue_images/'),
        ),
        migrations.AddField(
            model_name='venue',
            name='is_bookable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Maintenance', 'Maintenance'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
